"""add recurring_events table

Revision ID: 297b383d89f4
Revises: a3f7e2b1c4d5
Create Date: 2026-08-07 21:58:04.165631

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '297b383d89f4'
down_revision: str | None = 'a3f7e2b1c4d5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_settings_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('official_url', sa.String(length=500), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('time_of_day', sa.String(length=5), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('announcement_channel_id', sa.String(length=20), nullable=True),
    sa.Column('discussion_channel_id', sa.String(length=20), nullable=True),
    sa.Column('results_channel_id', sa.String(length=20), nullable=True),
    sa.Column('created_by_discord_user_id', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guild_settings_id'], ['guild_settings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('events', sa.Column('recurring_event_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'events', 'recurring_events', ['recurring_event_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'recurring_event_id')
    op.drop_table('recurring_events')
    # ### end Alembic commands ###
