"""add extra_data to linked_accounts

Revision ID: 766cb80bc491
Revises: 84fedc81c168
Create Date: 2026-08-08 23:25:26.851725

"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op



# revision identifiers, used by Alembic.
revision: str = '766cb80bc491'
down_revision: Union[str, None] = '84fedc81c168'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('linked_accounts', sa.Column('extra_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('linked_accounts', 'extra_data')
    # ### end Alembic commands ###
