"""Add linked_accounts table

Revision ID: 81bf5191a36a
Revises: 0001_initial
Create Date: 2026-08-06 23:07:21.073895

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "81bf5191a36a"
down_revision: str | None = "0001_initial"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "linked_accounts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("guild_member_id", sa.Integer(), nullable=False),
        sa.Column("platform", sa.String(length=50), nullable=False),
        sa.Column("handle", sa.String(length=255), nullable=False),
        sa.Column("normalized_handle", sa.String(length=255), nullable=False),
        sa.Column("profile_url", sa.String(length=255), nullable=False),
        sa.Column("validation_status", sa.String(length=20), nullable=False),
        sa.Column("current_rating", sa.Integer(), nullable=True),
        sa.Column("max_rating", sa.Integer(), nullable=True),
        sa.Column("global_rank", sa.Integer(), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_sync_status", sa.String(length=20), nullable=True),
        sa.Column("last_sync_error", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["guild_member_id"], ["guild_members.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("guild_member_id", "platform", name="uq_linked_account_platform"),
    )
    op.create_index(
        "ix_linked_accounts_normalized_handle",
        "linked_accounts",
        ["normalized_handle"],
        unique=False,
    )
    op.drop_index(op.f("ix_guild_settings_discord_guild_id"), table_name="guild_settings")
    op.create_index(
        op.f("ix_guild_settings_discord_guild_id"),
        "guild_settings",
        ["discord_guild_id"],
        unique=True,
    )
    op.drop_index(op.f("ix_users_discord_user_id"), table_name="users")
    op.create_index(op.f("ix_users_discord_user_id"), "users", ["discord_user_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_discord_user_id"), table_name="users")
    op.create_index(op.f("ix_users_discord_user_id"), "users", ["discord_user_id"], unique=False)
    op.drop_index(op.f("ix_guild_settings_discord_guild_id"), table_name="guild_settings")
    op.create_index(
        op.f("ix_guild_settings_discord_guild_id"),
        "guild_settings",
        ["discord_guild_id"],
        unique=False,
    )
    op.drop_index("ix_linked_accounts_normalized_handle", table_name="linked_accounts")
    op.drop_table("linked_accounts")
    # ### end Alembic commands ###
