"""add_guild_admins_table

Revision ID: 83219c87ae0c
Revises: c0da48701230
Create Date: 2026-08-09 01:14:23.728010

"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op



# revision identifiers, used by Alembic.
revision: str = '83219c87ae0c'
down_revision: Union[str, None] = 'c0da48701230'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guild_admins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_settings_id', sa.Integer(), nullable=False),
    sa.Column('discord_user_id', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guild_settings_id'], ['guild_settings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_settings_id', 'discord_user_id', name='uq_guild_admin')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guild_admins')
    # ### end Alembic commands ###
