"""add auto_create_events to guild_settings

Revision ID: 8afa0d36e103
Revises: 766cb80bc491
Create Date: 2026-08-09 00:02:13.851565

"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op



# revision identifiers, used by Alembic.
revision: str = '8afa0d36e103'
down_revision: Union[str, None] = '766cb80bc491'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guild_settings', sa.Column('auto_create_events', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('guild_settings', sa.Column('last_auto_event_run', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('guild_settings_discord_guild_id_key'), 'guild_settings', type_='unique')
    op.drop_constraint(op.f('users_discord_user_id_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_discord_user_id_key'), 'users', ['discord_user_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('guild_settings_discord_guild_id_key'), 'guild_settings', ['discord_guild_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('guild_settings', 'last_auto_event_run')
    op.drop_column('guild_settings', 'auto_create_events')
    # ### end Alembic commands ###
