"""reminders

Revision ID: 92dd1243aac9
Revises: 142129f09a28
Create Date: 2026-08-07 00:32:38.601261

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '92dd1243aac9'
down_revision: str | None = '142129f09a28'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_deliveries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_settings_id', sa.Integer(), nullable=False),
    sa.Column('contest_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.String(length=10), nullable=False),
    sa.Column('scheduled_for_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('discord_message_id', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['contest_id'], ['contests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['guild_settings_id'], ['guild_settings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_settings_id', 'contest_id', 'notification_type', name='uq_delivery_guild_contest_type')
    )
    op.add_column('guild_settings', sa.Column('reminders_enabled', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guild_settings', 'reminders_enabled')
    op.drop_table('notification_deliveries')
    # ### end Alembic commands ###
