"""add events tables

Revision ID: a3f7e2b1c4d5
Revises: 92dd1243aac9
Create Date: 2026-08-07 21:28:00.000000

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a3f7e2b1c4d5'
down_revision: str | None = '92dd1243aac9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_settings_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('official_url', sa.String(length=500), nullable=True),
    sa.Column('start_time_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('registration_deadline_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('announcement_channel_id', sa.String(length=20), nullable=True),
    sa.Column('discussion_channel_id', sa.String(length=20), nullable=True),
    sa.Column('results_channel_id', sa.String(length=20), nullable=True),
    sa.Column('announcement_message_id', sa.String(length=20), nullable=True),
    sa.Column('created_by_discord_user_id', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guild_settings_id'], ['guild_settings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_registrations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('guild_member_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['guild_member_id'], ['guild_members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'guild_member_id', name='uq_event_registration')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_registrations')
    op.drop_table('events')
    # ### end Alembic commands ###
