"""remove_recurring_events

Revision ID: c0da48701230
Revises: 8afa0d36e103
Create Date: 2026-08-09 00:38:13.551784

"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c0da48701230'
down_revision: Union[str, None] = '8afa0d36e103'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('events_recurring_event_id_fkey'), 'events', type_='foreignkey')
    op.drop_column('events', 'recurring_event_id')
    op.drop_table('recurring_events')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('recurring_event_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('events_recurring_event_id_fkey'), 'events', 'recurring_events', ['recurring_event_id'], ['id'], ondelete='SET NULL')
    op.create_table('recurring_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('guild_settings_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('platform', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('official_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('day_of_week', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('time_of_day', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('announcement_channel_id', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('discussion_channel_id', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('results_channel_id', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_by_discord_user_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['guild_settings_id'], ['guild_settings.id'], name=op.f('recurring_events_guild_settings_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('recurring_events_pkey'))
    )
    # ### end Alembic commands ###
